{% set version = "2.10.3" %}
{% set sha256 = "469c59fe71c81cdc41c84f842d62dd2739a08fac8cb85f5a518a92a6227e2ed6" %}

package:
  name: imageio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imageio/imageio-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - imageio_download_bin = imageio.__main__:download_bin_main
    - imageio_remove_bin = imageio.__main__:remove_bin_main

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python >=3.7
    - numpy
    - pillow >=8.3.2

test:
  imports:
    - imageio
    - imageio.config
  commands:
    - imageio_download_bin -h
    - imageio_remove_bin -h
    - pip check
  requires:
    - pip

about:
  home: https://imageio.github.io
  doc_url: https://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: A Python library for reading and writing image data
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - almarklein
    - blink1073
    - jni
