{% set name = "imageio" %}
{% set version = "2.37.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0212ef2727ac9caa5ca4b2c75ae89454312f440a756fcfc8ef1993e718f50f8a

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - imageio_download_bin = imageio.__main__:download_bin_main
    - imageio_remove_bin = imageio.__main__:remove_bin_main

requirements:
  host:
    - pip
    - python
    - setuptools >=61.0
    # - numpy {{ numpy }}
  run:
    - python
    - numpy
    - pillow >=8.3.2

# imageio-ffmpeg package is not available in channel
# E       KeyError: 'imageio.plugins.ffmpeg'
{% set deselect_tests = "--deselect=tests/test_format.py::test_preferring_arbitrary" %}
# E       AssertionError: assert 'NPZ' == 'FFMPEG'
{% set deselect_tests = deselect_tests + " --deselect=tests/test_format.py::test_missing_format" %}

test:
  source_files:
    - tests
  imports:
    - imageio
    - imageio.config
    - imageio.core
    - imageio.plugins
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests {{ deselect_tests }}
    - imageio_download_bin -h
    - imageio_remove_bin -h
  requires:
    - pip
    - pytest
    - fsspec
    - aiohttp
    - requests

about:
  home: https://github.com/imageio/imageio
  doc_url: https://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: A Python library for reading and writing image data
  description: |
    Imageio is a Python library that provides an easy interface to read and write a wide range of
    image data, including animated images, video, volumetric data, and scientific formats.
  license_file: LICENSE
  license_family: BSD
  license: BSD-2-Clause

extra:
  recipe-maintainers:
    - almarklein
    - blink1073
    - jni
