{% set name = "imageio" %}
{% set version = "2.37.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 0212ef2727ac9caa5ca4b2c75ae89454312f440a756fcfc8ef1993e718f50f8a

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - imageio_download_bin = imageio.__main__:download_bin_main
    - imageio_remove_bin = imageio.__main__:remove_bin_main

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=61.0
  run:
    - python
    - numpy
    - pillow >=8.3.2
  run_constrained:
    - numpy >2

test:
  imports:
    - imageio
    - imageio.config
  commands:
    - imageio_download_bin -h
    - imageio_remove_bin -h
    - pip check
  requires:
    - pip

about:
  home: https://imageio.github.io
  doc_url: https://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: A Python library for reading and writing image data
  description: |
    Imageio is a Python library that provides an easy interface to read and write a wide range of
    image data, including animated images, video, volumetric data, and scientific formats.
  license_file: LICENSE
  license_family: BSD
  license: BSD-2-Clause

extra:
  recipe-maintainers:
    - almarklein
    - blink1073
    - jni
