{% set version = "2.13.5" %}
{% set sha256 = "c7ec2be58e401b6eaa838f8eaf8368ed54b2de4a1b001fe6551644f1a30a843d" %}

package:
  name: imageio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/imageio/imageio-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - imageio_download_bin = imageio.__main__:download_bin_main
    - imageio_remove_bin = imageio.__main__:remove_bin_main

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - numpy
    - pillow

test:
  imports:
    - imageio
  commands:
    - imageio_download_bin -h
    - imageio_remove_bin -h

about:
  home: https://imageio.github.io
  doc_url: https://imageio.readthedocs.io
  dev_url: https://github.com/imageio/imageio
  summary: A Python library for reading and writing image data
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
    - blink1073
    - jni