# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "l+moX1QEWtw0L2ph05YvYPeg2PxTWeH1+3/C6aUSFtzoitdTEWGftmhmybb98AGk/KCoTvT6Lj3bd/p7M0cdK4yoy7lkpx6oVZGSuKm3gyS0L11mmzAFIDDBMJJiPrMTZBkQJA5ErR37rOT7y4a4X+vruJLAVsazAZ0kRc0CcZlL9hF/0Uv8ozeV0iMkbS67XZi1ScNvlKhmJq+OgLM2Q5zpLhsPr+T7FgDqIU8K6Ry1XIKj60PdAYF3ifrRj3WSHgeF9WzIYvdfTOe6nFb7IjD2K7GVQIuzzmdWojHSIE1ovDZBiJ8bEsdHD3dzetxa7gXbBWJrO+zwL3yxf8s4P+tOLssp06PtNuCPOaJhyVV7TDLzfmjp2fmdNixTx10INJszhV2s5VYUE90C60GcqMhPuigorLtDzGl0W+MpLm1oqDoKPn7j6W8RFq+Kc2saaPL9Swvm16QKqM+Ci3Kbj5Wr/pPJ7kM7JBzkxyrbna1OjrSX+w5ke8dKqQZszVcATCIjUcDw7C7gQ3+P5VkRV2b4MrDaDRQS8UYeGVNEDNBDqXyjWosT4mrD7fS82LYebqIrKRZmVNr/xZPf8YGJfSQhvTo+wG3kuVaBRDHyK51l6bVbFO4EZdlkZc1A+Lt/+vpGg7jnA8qDUIehS2g9lsSagYRrr93uN0iVscVcTvI="


before_install:
    # Remove homebrew.
    - brew remove --force --ignore-dependencies $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
