travis:
  secure:
    BINSTAR_TOKEN: l+moX1QEWtw0L2ph05YvYPeg2PxTWeH1+3/C6aUSFtzoitdTEWGftmhmybb98AGk/KCoTvT6Lj3bd/p7M0cdK4yoy7lkpx6oVZGSuKm3gyS0L11mmzAFIDDBMJJiPrMTZBkQJA5ErR37rOT7y4a4X+vruJLAVsazAZ0kRc0CcZlL9hF/0Uv8ozeV0iMkbS67XZi1ScNvlKhmJq+OgLM2Q5zpLhsPr+T7FgDqIU8K6Ry1XIKj60PdAYF3ifrRj3WSHgeF9WzIYvdfTOe6nFb7IjD2K7GVQIuzzmdWojHSIE1ovDZBiJ8bEsdHD3dzetxa7gXbBWJrO+zwL3yxf8s4P+tOLssp06PtNuCPOaJhyVV7TDLzfmjp2fmdNixTx10INJszhV2s5VYUE90C60GcqMhPuigorLtDzGl0W+MpLm1oqDoKPn7j6W8RFq+Kc2saaPL9Swvm16QKqM+Ci3Kbj5Wr/pPJ7kM7JBzkxyrbna1OjrSX+w5ke8dKqQZszVcATCIjUcDw7C7gQ3+P5VkRV2b4MrDaDRQS8UYeGVNEDNBDqXyjWosT4mrD7fS82LYebqIrKRZmVNr/xZPf8YGJfSQhvTo+wG3kuVaBRDHyK51l6bVbFO4EZdlkZc1A+Lt/+vpGg7jnA8qDUIehS2g9lsSagYRrr93uN0iVscVcTvI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
